# Generated by Django 4.1 on 2022-08-22 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Box",
            fields=[
                ("_id", models.AutoField(primary_key=True, serialize=False)),
                ("capacity", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Freezer",
            fields=[
                ("_id", models.AutoField(primary_key=True, serialize=False)),
                ("capacity", models.IntegerField()),
                ("name", models.CharField(max_length=200)),
                ("shelves", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("dob", models.DateField()),
                ("gender", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Rack",
            fields=[
                ("_id", models.AutoField(primary_key=True, serialize=False)),
                ("capacity", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Shelf",
            fields=[
                ("_id", models.AutoField(primary_key=True, serialize=False)),
                ("capacity", models.IntegerField()),
                ("name", models.CharField(max_length=200)),
                ("racks", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Study",
            fields=[
                ("_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Sample",
            fields=[
                ("_id", models.AutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=100)),
                ("date_of_archive", models.DateField()),
                (
                    "patient_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="biobank.patient",
                    ),
                ),
                (
                    "study_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="biobank.study"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="patient",
            name="study_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="biobank.study"
            ),
        ),
        migrations.CreateModel(
            name="Cube",
            fields=[
                ("_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "box_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="biobank.box"
                    ),
                ),
                (
                    "freezer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="biobank.freezer",
                    ),
                ),
                (
                    "rack_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="biobank.rack"
                    ),
                ),
                (
                    "shelf_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="biobank.shelf"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="box",
            name="freezer_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="biobank.freezer"
            ),
        ),
        migrations.AddField(
            model_name="box",
            name="rack_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="biobank.rack"
            ),
        ),
        migrations.AddField(
            model_name="box",
            name="shelf_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="biobank.shelf"
            ),
        ),
    ]
